<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf9efc1d9ceb82e6318bd3ef2f6e6db4
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf9efc1d9ceb82e6318bd3ef2f6e6db4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf9efc1d9ceb82e6318bd3ef2f6e6db4::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
